version: '3.6'
services:
  # Application-wide auth server
  iot-auth-server:
    image: dougflynn/iot-auth-server:latest
    # build: iot-auth-server
    # depends_on:
      #   - database
    deploy:
      replicas: 2

    ports:
      - "8000:8000"
    env_file:
      # Needs access to DB
      - .db.env
    networks:
      iot-proxy:
      iot-backend:
        aliases:
          - iot-auth-server

  iot-api-plants:
    image: dougflynn/iot-api-plants:latest
    # build: iot-api-plants
    # depends_on:
    #   - database
    deploy:
      replicas: 1

    ports:
      - "8001:8001"
    networks:
      iot-proxy:
      iot-backend:
        aliases:
          - iot-api-plants

  iot-mqtt-hub:
    image: dougflynn/iot-mqtt-hub:latest
    # build: iot-mqtt-hub
    # depends_on:
    #   - database
    deploy:
      replicas: 1
    ports:
      - 8002:8002
    volumes:
      - "./iot-mqtt-hub:/app"
    networks:
      iot-backend:
        aliases:
          - iot-mqtt-hub

  iot-mqtt-broker:
    image: eclipse-mosquitto
    deploy:
      replicas: 1
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./iot-mqtt-hub:/app"
    networks:
      iot-backend:
        aliases:
          - iot-mqtt-broker

  # Currently using hosted mongo, don't need this anymore
  # database:
  #   image: mongo
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         # HDD is currently attached to manager pi
  #         - "node.role==manager"
  #   ports:
  #     - 27017:27017
  #   env_file:
  #     - .db.env
  #   volumes:
  #     # change depending on how your pi is setup
  #     - /home/manager/mounts/hdd0/iot-db:/data/db
  #   networks:
  #     iot-backend:
  #       aliases:
  #         - mongo-db

networks:
  iot-backend:
  iot-proxy:
    external: true