version: '3.7'
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    labels:
      # Register dashboard service
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"

      # Declare/use dashboard auth middleware - prod
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=traefik_users"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - iot-backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  iot-api-plants:
    image: iot-api-plants
    build:
      context: iot-api-plants
      dockerfile: Dockerfile.prod
    # depends_on:
    #   - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iot-api-plants.entrypoints=web"
      - "traefik.http.routers.iot-api-plants.service=iot-api-plants"
      - "traefik.http.services.iot-api-plants.loadbalancer.server.port=8000"

      # Listen on path
      - "traefik.http.routers.iot-api-plants.rule=PathPrefix(`/iot-plants`)"
      # Strip path after match
      - "traefik.http.middlewares.api-plants-pathstrip.stripprefix.prefixes=/iot-plants"

      # Register path strip middleware
      - "traefik.http.routers.iot-api-plants.middlewares=api-plants-pathstrip@docker"
    networks:
      iot-backend:
        aliases:
          - iot-api-plants

  # Application-wide auth server
  iot-auth-server:
    image: iot-auth-server
    build:
      context: iot-auth-server
      dockerfile: Dockerfile.prod
    # depends_on:
    #   - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iot-auth-server.entrypoints=web"
      - "traefik.http.routers.iot-auth-server.service=iot-auth-server"
      - "traefik.http.services.iot-auth-server.loadbalancer.server.port=8001"

      # Listen on path
      - "traefik.http.routers.iot-auth-server.rule=PathPrefix(`/iot-auth`)"
      # Strip path after match
      - "traefik.http.middlewares.auth-server-pathstrip.stripprefix.prefixes=/iot-auth"

      # Register path strip middleware
      - "traefik.http.routers.iot-auth-server.middlewares=auth-server-pathstrip@docker"
    networks:
      iot-backend:
        aliases:
          - iot-auth-server

  # Not doing anything yet, but still needed
  database:
    image: mongo
    env_file:
      - .db.env

networks:
  iot-backend: