version: '3'
services:
  iot-api-plants:
    # Local deploy to docker swarm, shouldn't be a security issue unless I ever take this off LAN
    image: 127.0.0.1:5000/iot-api-plants
    build: iot-api-plants
    depends_on:
      - database
    networks:
      iot-backend:
        aliases:
          - iot-api-plants
  # Not doing anything yet, but still needed
  database:
    image: postgres
  proxy:
    image: nginx
    volumes:
    - ./nginx/templates:/etc/nginx/templates
    ports:
    - "8106:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
      - iot-api-plants
    networks:
      iot-backend:
        aliases:
          - iot-router

networks:
  iot-backend: