version: '3.6'
services:
  # Application-wide auth server
  iot-auth-server:
    image: dougflynn/iot-auth-server:latest
    build: iot-auth-server
    # depends_on:
      #   - database
    deploy:
      replicas: 2

    ports:
      - "8000:8000"
    networks:
      iot-proxy:
      iot-backend:
        aliases:
          - iot-auth-server

  iot-api-plants:
    image: dougflynn/iot-api-plants:latest
    build: iot-api-plants
    # depends_on:
    #   - database
    deploy:
      replicas: 1

    ports:
      - "8001:8001"
    networks:
      iot-proxy:
      iot-backend:
        aliases:
          - iot-api-plants


  # Not doing anything yet, but still needed
  database:
    image: mongo
    env_file:
      - .db.env
    deploy:
      replicas: 1

# Persistent https certs

networks:
  iot-backend:
  iot-proxy:
    external: true