version: '3.6'
services:
  # Application-wide auth server
  iot-auth-server:
    image: iot-auth-server
    build: iot-auth-server
    # depends_on:
    #   - database
    ports:
      - 8000:8000
    env_file:
      # Needs access to DB
      - .db.env
    volumes:
      - "./iot-auth-server:/app"
    networks:
      iot-backend:
        aliases:
          - iot-auth-server

  iot-api-plants:
    image: iot-api-plants
    build: iot-api-plants
    # depends_on:
    #   - database
    ports:
      - 8001:8001
    volumes:
      - "./iot-api-plants:/app"
    networks:
      iot-backend:
        aliases:
          - iot-api-plants

  iot-mqtt-hub:
    image: iot-mqtt-hub
    build: iot-mqtt-hub
    # depends_on:
    #   - database
    ports:
      - 8002:8002
    volumes:
      - "./iot-mqtt-hub:/app"
    networks:
      iot-backend:
        aliases:
          - iot-mqtt-hub

  iot-mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./iot-mqtt-hub:/app"
    networks:
      iot-backend:
        aliases:
          - iot-mqtt-broker



  # Not doing anything yet, but still needed
  database:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .db.env
    networks:
      iot-backend:
        aliases:
          - mongo-db
    volumes:
      - ./db-data:/data/db

networks:
  iot-backend: