version: '3.6'
services:
  # Application-wide auth server
  forward-auth-server:
    image: iot-auth-server
    build: iot-auth-server
    # depends_on:
    #   - database
    ports:
      - 8000:8000
    volumes:
      - "./iot-auth-server:/app"
    networks:
      iot-backend:
        aliases:
          - forward-auth-server

  iot-api-plants:
    image: iot-api-plants
    build: iot-api-plants
    # depends_on:
    #   - database
    ports:
      - 8001:8001
    volumes:
      - "./iot-api-plants:/app"
    networks:
      iot-backend:
        aliases:
          - iot-api-plants


  # Not doing anything yet, but still needed
  database:
    image: mongo
    env_file:
      - .db.env
    networks:
      iot-backend:
        aliases:
          - mongo-db

networks:
  iot-backend: