FROM debian:stretch-slim

# Needed for ssl cargo deps
RUN apt-get update && \
  apt-get install libssl-dev pkg-config lsb-release -y && \
  apt-get autoremove

WORKDIR /app

COPY ./Rocket.toml ./

COPY ./target/x86_64-unknown-linux-musl/release/iot-auth ./

CMD ["./iot-auth"]
